# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d5641ed6d3c5587d4a35127baf10ce3689d764c3375435b06e40f016144a01847b94b3f1054c51164004d87a924814dba00e19e186b4223c5c5db4ffdf967e

test:
  secret_key_base: d863c16ce7328c0e6b67bb081fed40b419131977a04512747226073cbada61fe6172e98badf1b70f76e494057068c3226e14427fd7ff320c297cdc8b46109c41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
